os: osx 
language: generic
osx_image: xcode11.3
before_script: 
 - brew update 
 - brew install automake autoconf libtool wget libimobiledevice
 - brew unlink usbmuxd 
 - brew install --HEAD usbmuxd 
 - brew unlink usbmuxd 
 - brew link usbmuxd
 - brew unlink libimobiledevice
 - brew install --HEAD libimobiledevice 
 - brew install ideviceinstaller 
 - brew install ios-deploy 
 - git clone https://github.com/flutter/flutter.git -b beta --depth 1 
script: 
 - flutter/bin/flutter build ios --debug --no-codesign --verbose
cache: 
  directories: 
  - $HOME/.pub-cache
before_deploy: 
  - pushd build/ios/iphoneos 
  - mkdir Payload 
  - cd Payload 
  - ln -s ../Runner.app 
  - cd .. 
  - zip -r app.ipa Payload 
  - popd
deploy:
  cleanup: false
  skip_cleanup: true
  provider: releases
  name: Travis CI auto release
  prerelease: true
  on:
    repo: NovySoft/novyNaplo
  token:
    secure: nrH0NT6zZPklkK20788D073/dWsG65/C3+wQRU039gOiIjoPHsbsWyvPww12CQ3d52GEOHfw9h36qTJXGtjaXQ0AvVboMD+gV9Kmtt5uPrnpuVhhKRAYV+jm56AEaLOJCDu8FoDBKheDsvZhObmwmk7l1fjSJyx7iEA0ztHrRrYNf8yGZ5Wtbz6FHn2s9b067Hk32W2TvROGBIBumtrlQLufM7XP6Up042X6DJfOVEcVgJ6peazSF/PT7WNZ/nymXav3xld94h0T787TSWB24/leCowlmiVLVCbYxWAX2TMgGZmhxHGwQK4nMAeHcVj/y2+hfBUjn1cGJXvMrK97N9cIhddOGFDl6QOp/rHzKg179ka/8jUnVhlONdfEd1+4HH4w0NhiSlguxtXa3nig/E0vvUNm+IS2faH9A6VReNtkyv7cWegE55ZZsCD8XZnq63jGb79WngyVzir7jlBpPQ2Lv8dwnja9/GHN4kSdLfOR0v2aklKFGWMy+TKqnW9GHclohl/n7lpURIlPDHjxP84BOEnnkgUv+N6Wzo8p9j77R7hm+m247muQkHU0xt2EybOF3faOfH+6HBxSJj30Dnff0W0JuqI3Oi8gZAn6EyLdRiAniUWmYReD7HjVRypdLaH8vkCrrfaqewIYOnrqPdtaSRxyZtJ5kfglbCrr4wI=
  file: "/build/ios/iphoneos/app.ipa"