matrix:
  include:
    - name: Build and release apk
      os: linux
      dist: trusty
      jdk: oraclejdk8
      language: node_js
      node_js:
        - '12'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
        packages:
          - lib32stdc++6
          - libstdc++6
          - curl
      cache:
        directories:
          - "$HOME/.pub-cache"
          - node_modules
      install:
        - echo install
        - npm install
        - cd travis
        - export GIT_MESSAGE=`git log -1 --pretty=%B`
        - node discord.js starting
        - cd /home/travis/build/NovySoft/novyNaplo
      before_script:
        - cd /home/travis/build/NovySoft/novyNaplo
        - wget https://services.gradle.org/distributions/gradle-5.4.1-all.zip
        - unzip -qq gradle-5.4.1-all.zip
        - export GRADLE_HOME=`pwd`/gradle-5.4.1
        - export PATH=$GRADLE_HOME/bin:$PATH
        - mkdir -p /home/travis/.android
        - echo 'count=0' > /home/travis/.android/repositories.cfg
        - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        - mkdir android-sdk-tools
        - unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
        - export PATH=`pwd`/android-sdk-tools/tools/bin:$PATH
        - mkdir -p $ANDROID_SDK_ROOT
        - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository"
          > /dev/null
        - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
        - sdkmanager --list
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
      script:
        - flutter doctor -v
        - flutter pub get
        - cd android
        - wget "$KEYPROPERTIES" -O key.properties &> /dev/null
        - cd app
        - wget "$KEYJKS" -O key.jks &> /dev/null
        - cd /home/travis/build/NovySoft/novyNaplo
        - "./flutter/bin/flutter build apk --verbose"
      after_success:
        - cd travis
        - node discord.js success
        - cd /home/travis/build/NovySoft/novyNaplo
      before_deploy:
        - git config --local user.name "$GITUSER"
        - git config --local user.email "$GITEMAIL"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        cleanup: false
        skip_cleanup: true
        provider: releases
        name: Travis CI auto release
        prerelease: true
      on:
        repo: NovySoft/novyNaplo
      token:
        secure: nrH0NT6zZPklkK20788D073/dWsG65/C3+wQRU039gOiIjoPHsbsWyvPww12CQ3d52GEOHfw9h36qTJXGtjaXQ0AvVboMD+gV9Kmtt5uPrnpuVhhKRAYV+jm56AEaLOJCDu8FoDBKheDsvZhObmwmk7l1fjSJyx7iEA0ztHrRrYNf8yGZ5Wtbz6FHn2s9b067Hk32W2TvROGBIBumtrlQLufM7XP6Up042X6DJfOVEcVgJ6peazSF/PT7WNZ/nymXav3xld94h0T787TSWB24/leCowlmiVLVCbYxWAX2TMgGZmhxHGwQK4nMAeHcVj/y2+hfBUjn1cGJXvMrK97N9cIhddOGFDl6QOp/rHzKg179ka/8jUnVhlONdfEd1+4HH4w0NhiSlguxtXa3nig/E0vvUNm+IS2faH9A6VReNtkyv7cWegE55ZZsCD8XZnq63jGb79WngyVzir7jlBpPQ2Lv8dwnja9/GHN4kSdLfOR0v2aklKFGWMy+TKqnW9GHclohl/n7lpURIlPDHjxP84BOEnnkgUv+N6Wzo8p9j77R7hm+m247muQkHU0xt2EybOF3faOfH+6HBxSJj30Dnff0W0JuqI3Oi8gZAn6EyLdRiAniUWmYReD7HjVRypdLaH8vkCrrfaqewIYOnrqPdtaSRxyZtJ5kfglbCrr4wI=
      file: "/home/travis/build/NovySoft/novyNaplo/build/app/outputs/apk/release/app-release.apk"
      after_deploy:
        - cd travis
        - git fetch --tags
        - node discord.js deployed
        - cd /home/travis/build/NovySoft/novyNaplo
      after_failure:
        - cd travis
        - node discord.js fail
        - cd /home/travis/build/NovySoft/novyNaplo

    - name: Build an ipa to test ios integrity
      os: osx
      language: generic
      osx_image: xcode8.3
      before_script:
        - pip install six
        - brew update
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign