os: linux
dist: trusty
jdk: oraclejdk8
language: node_js
node_js:
- '12'
env:
  global:
  - ANDROID_SDK_ROOT=/opt/android
  - secure: xitEwUvSNy537tr3DUq/lcuc6Vkw81Cg+7miECwm0tg0S8s5vn3ZMU0v9U9He+Y9r/S0asi3CNMO7x1pnPPAY9YXXsYn/DUULvPz99vMhamTZ905DMG5fAlyqxHwjZnp/CUYGibJdVvO1OkjXl5P4IR/uZxAGjSULhSEhbW0cXHtAvuJ5sVdAg3bIxu20pmzEK3vZzOoX/mfIRWk3mbIlPNv5IA/FGpnpUZLMl+nTD+mdmDpq0OEUgZLfLp7CYHzda9gBe6G/KH7gbjzS74Yb5E7UJlFhKjY7SwTPAnDfAAqDZm93JVlfI+pMFpWrtxA1xFQmWFIm3JDkeOIxeI09em0DqIRfgDRzch4LKc2O/BJg87lkevuuQ7yl4s2mBmXoaWi6kX+GTURyFnp+ogGIXmlyRrzLy+QgPcJFG6TA/wHOHhw4U7G8UnI5NTrz63lTALB3NL4nshIt+4tbcecyPWv3uP7nc5jILm7+lrC4c7GnwXJ0zQq6VkrchQ+Kl+a7NUUQpcXE/8b2i/nvUCqHBPKwHlwVhkhtIge+3e8LZmQkbRoUDxkkpALS1HSkePJMvbv/mznjy/hYuqxw2VoAPMZ+qSvqA674fYRA3GJp6l63d40vcjd1m2V3Y9Q87AdhBCJYnu/kRZQoj5E9h9ShYkD0zrKM2G71lCmmUgBCz8=
  - secure: DkJHr1zDkt5QMpzhw53utwryTucd73m6VnDnMvYhNma1272u4WdjODt4TNb4XS/340qoE2S59pP4IdACucbINmL5c2hqVvV43NMlE9aKSVUCkIdcDEAFxY561WfKBFqo18f/iPpMMW4pRj7INDs1usHkDbzLloG63elMWOygB2Bvig2lE6ztC+l7J7o+SKVrEFXRIjkfIwfx6dKCocQD6dZn+y5MDMsE7R+Z54VplZZNQ8nKZoIVSA38ZUmhBSqM47eKgZ+F/Z6KNx/C7GdSkIREze3+EeZ3zR9jxtUVH/m+iqWfLYlpiHt9gH3GlnqfUtR/LmQmt8UB0G5pmNrpo/YIDCY+HYMDgN4YJTLbPzWvfXosUtI6/FrAXxgUXuwhL8ASo3Xrvn+XgJBjKPKA0rGB7cy1i+iW2B5IweHbCBFpsYb+rEryt+X+h+GpK+DBJ0gVC4LcWQbJ6Q8aI0YA5Au8PudH9fhPKt2ahMKtT+xd75d7eFqnuHeSnnTN1Gy12Ix/ilxt7P+Tscgxvxl1NewWGKsBfsOdlbCDX3jFRG88fqOAmS46FT0fyzfzxtS2L8yKfI7mUZwilRJlyAfvO91S0IY8l5USIo0lF9nFHCk3mxzryp8O/HKomcHWTM063lDSl5DFkiIYAX89d5+3zhv6hssZkQR90sDjy3gmHAk=
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32stdc++6
    - libstdc++6
    - curl
cache:
  directories:
  - "$HOME/.pub-cache"
  - node_modules
before_script:
- wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
- unzip -qq gradle-4.10.3-bin.zip
- export GRADLE_HOME=`pwd`/gradle-4.10.3
- export PATH=$GRADLE_HOME/bin:$PATH
- mkdir -p /home/travis/.android
- echo 'count=0' > /home/travis/.android/repositories.cfg
- wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
- mkdir android-sdk-tools
- unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
- export PATH=`pwd`/android-sdk-tools/tools/bin:$PATH
- mkdir -p $ANDROID_SDK_ROOT
- yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository"
  > /dev/null
- export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
- sdkmanager --list
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
script:
- flutter doctor -v
- flutter pub get
- pwd
- "./flutter/bin/flutter build apk"
after_success:
- export AUTHOR_NAME=`git log -1 "$TRAVIS_COMMIT" --pretty="%aN"`
- export COMMITTER_NAME=`git log -1 "$TRAVIS_COMMIT" --pretty="%cN"`
- export COMMIT_SUBJECT=`git log -1 "$TRAVIS_COMMIT" --pretty="%s"`
- export COMMIT_MESSAGE=`git log -1 "$TRAVIS_COMMIT" --pretty="%b"`
