name: novynaplo_v2
description: NovyNapló V2
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: 2.2.0
  theme_provider: 0.6.0
  logger: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icon.png"
  ios: true
  image_path_ios: "assets/icon_ios.jpg"

flutter:
  uses-material-design: true
