name: novynaplo
description: Novy&#x27;s Unofficial Ekreta Client

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+21
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: any
  cupertino_icons: any
  web_socket_channel: any
  http: any
  flutter_launcher_icons: any
  shared_preferences: any
  encrypt: 5.0.1
  connectivity: any
  flutter_spinkit: any
  dynamic_theme:
    git: https://github.com/bartektartanus/dynamic_theme.git
  firebase_crashlytics: any
  firebase_analytics: any
  charts_flutter:
    git: https://github.com/Legolaszstudio/charts
  firebase_performance: any
  url_launcher: any
  material_design_icons_flutter: any
  flutter_icons: ^1.1.0
  sqflite: any
  animations: any
  flutter_html: 2.2.1
  customgauge: any
  flutter_slidable: 1.3.0
  flutter_local_notifications: 9.5.3
  flutter_svg: 0.22.0
  json_table: any
  flutter_calendar_week:
    git:
      url: https://github.com/mduccc/flutter_calendar_week
      ref: 0.4.1
  path_provider: any
  open_file: any
  fluttertoast: 8.0.9
  flutter_linkify: any
  introduction_screen: any
  flutter_colorpicker: ^1.0.3
  rsa_pkcs: ^2.0.1
  flutter_markdown: ^0.6.10
  android_alarm_manager_plus: ^2.0.5
  platform: ^3.1.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_localizations:
  sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  mockito: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/novy.jpg
    - assets/home.png
    - assets/error.png
    - assets/git.png
    - assets/firebase.png
    - assets/icon/icon.png

  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
