// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsJLTcjRJ2lQi6P2xnuiCeaTEC3oZE2oc',
    appId: '1:362994109207:android:3b94aeac152489e2480552',
    messagingSenderId: '362994109207',
    projectId: 'novynaplo-152ec',
    databaseURL: 'https://novynaplo-152ec.firebaseio.com',
    storageBucket: 'novynaplo-152ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHIWqutnvL5fUuSY8cvLqyerc5328a0o',
    appId: '1:362994109207:ios:6475f71943f0bce9480552',
    messagingSenderId: '362994109207',
    projectId: 'novynaplo-152ec',
    databaseURL: 'https://novynaplo-152ec.firebaseio.com',
    storageBucket: 'novynaplo-152ec.appspot.com',
    androidClientId: '362994109207-t8k5firkkfi37uvlj87lf3k4tutuc8v2.apps.googleusercontent.com',
    iosClientId: '362994109207-oj8phs2l6v3qb8ndjnlvrkmc2rh10lk6.apps.googleusercontent.com',
    iosBundleId: 'novy.vip.novynaplo',
  );
}
