name: flutter

on: [push, pull_request]

jobs:
  analyze:
      name: Analyze
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      
      
  buildAndroid:
    name: Build apk for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Setup keystore
        env:
          KEYJKS: ${{ secrets.KEYJKS }}
          KEYPROPERTIES: ${{ secrets.KEYPROPERTIES }}
        run: |
          cd android
          wget "$KEYPROPERTIES" -O key.properties
      - name: Build apk
        run: flutter build apk --no-shrink --release --verbose